### ISSUE TITLE
Research: Minting Zealousness

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/uad-contracts#40]
@hpiyankov you expressed concerns about how our protocol may not mint fast enough with low demand. Can you spend a couple weeks on researching a solution when you're back from vacation?

cc: @ubiquity/research

**Comment by hpiyankov** [comment]
This issue is related to this one - https://github.com/ubiquity/uad-contracts/issues/26

Are we saying that we need an alternative solution to the one proposed there?
